//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Elever_Klasse.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Elevliste
    {
        public string Navn { get; set; }
        public string Klasse { get; set; }
        public Nullable<int> Alder { get; set; }
        public int ID { get; set; }
    }
}
